name: Run Tests

on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - 'go.*'
      - '_fixture/**'
      - '.github/**'
      - 'codecov.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - 'go.*'
      - '_fixture/**'
      - '.github/**'
      - 'codecov.yml'

jobs:
  test:
    env:
      latest: '1.17'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.14', '1.15', '1.16', '1.17']
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run static checks
        if: matrix.go == env.latest && matrix.os == 'ubuntu-latest'
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck -tests=false ./...

      - name: Run Tests
        run: |
          go test -race --coverprofile=coverage.coverprofile --covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: success() && matrix.go == env.latest && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
  benchmark:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.17]
    name: Benchmark comparison ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code (Previous)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: previous

      - name: Checkout Code (New)
        uses: actions/checkout@v2
        with:
          path: new

      - name: Install Dependencies
        run: go get -v golang.org/x/perf/cmd/benchstat

      - name: Run Benchmark (Previous)
        run: |
          cd previous
          go test -run="-" -bench=".*" -count=8 ./... > benchmark.txt

      - name: Run Benchmark (New)
        run: |
          cd new
          go test -run="-" -bench=".*" -count=8 ./... > benchmark.txt

      - name: Run Benchstat
        run: |
          benchstat previous/benchmark.txt new/benchmark.txt
