version: "3"

services:
  dev-env:
    container_name: Q-n-A_dev-env
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/Q-n-A:cached
    command: sleep infinity
    ports:
      - "9000:9000"
      - "9060:6060"
    depends_on:
      - mariadb

  frontend:
    container_name: Q-n-A_frontend
    build:
      context: ../dev
      dockerfile: Dockerfile
    volumes:
      - ../frontend/devcontainer/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "9001:80"
    depends_on:
      - dev-env

  mariadb:
    container_name: Q-n-A_mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Q-n-A
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: Q-n-A_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "9100:80"
    depends_on:
      - mariadb

volumes:
  db:
