name: dev_build

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: q-n-a
  IMAGE_TAG: master
  DEPLOY_REPO: https://github.com/Q-n-A-dev-team/dev-deploy

jobs:
  build:
    name: Build Docker Image
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  scan:
    name: Scan Image Vulnerability
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull ghcr.io/traptitech/${IMAGE_NAME}:${IMAGE_TAG}
      - name: Container image scan
        uses: Azure/container-scan@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Create PR to dev-deploy repo
    runs-on: ubuntu-latest
    needs: [build, scan]
    steps:
      - name: Clone dev-deploy repository
        run: git clone ${{ env.DEPLOY_REPO }}
      - name: Make log file
        run: |
          mkdir -p deploy-log/backend
          echo "Deployment of backend-${{ github.sha }}" >> deploy-log/backend/${{ github.sha }}.txt
      - name: Checkout to another branch
        run: |
          git checkout -b backend-${{ github.sha }}
      - name: git setting
        run: |
          git config --local user.email "git@github.com"
          git config --local user.name "Q'n'A backend"
      - name: Commit & push files
        run: |
          git commit -m "Requesting deployment of backend-${{ github.sha }}" -a
          git push origin backend-${{ github.sha }}
      - name: Create pull request
        run: gh pr create -R ${{ env.DEPLOY_REPO }} -H backend-${{ github.sha }} -t "Requesting deployment of backend-${{ github.sha }}"
        env:
          AUTHOR: ${{ github.event.pusher.name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
