name: dev_build

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: q-n-a
  IMAGE_TAG: master
  DEPLOY_REPO: dev-deploy
  SIDE: frontend

jobs:
  build:
    name: Build Docker Image
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/q-n-a-dev-team/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  scan:
    name: Scan Image Vulnerability
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull ghcr.io/q-n-a-dev-team/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Container image scan
        uses: Azure/container-scan@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/q-n-a-dev-team/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Create PR to dev-deploy repo
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setting up repository
        uses: actions/checkout@v2
        with:
          repository: Q-n-A-dev-team/${{ env.DEPLOY_REPO }}
          token: ${{ secrets.DEPLOY_PAT }}
          persist-credentials: false
          fetch-depth: 0
      - name: Setting up git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "Q'n'A-${{ env.SIDE }}"
      - name: Make log file
        run: |
          mkdir -p deploy-log/${{ env.SIDE }}
          echo "Deployment of ${{ env.SIDE }}-${{ github.sha }}" >> deploy-log/${{ env.SIDE }}/${{ github.sha }}.txt
      - name: Commit
        run: |
          git checkout -b ${{ env.SIDE }}-${{ github.sha }}
          git add .
          git commit -m "Requesting deployment of ${{ env.SIDE }}-${{ github.sha }}"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOY_PAT }}
          branch: ${{ env.SIDE }}-${{ github.sha }}
          repository: Q-n-A-dev-team/${{ env.DEPLOY_REPO }}
      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_PAT }}
        run: gh pr create -R Q-n-A-dev-team/${{ env.DEPLOY_REPO }} -H ${{ env.SIDE }}-${{ github.sha }} -t "Requesting deployment of ${{ env.SIDE }}" -b "On ${{ github.sha }}"
